server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Configurazione essenziale per Angular (SPA fallback)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Ottimizzazione cache per file statici (JS/CSS)
    location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Ottimizzazione cache per immagini e media
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
}
